"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { RoadmapTimeline } from "@/components/student/RoadmapTimeline";
import { MetricCard } from "@/components/cards/MetricCard";
import { StatusBadge } from "@/components/cards/StatusBadge";
import { LearningRoadmap } from "@/lib/models/roadmap.model";
import { Map, Target, BookOpen, MessageSquare, Zap } from "lucide-react";
import Link from "next/link";
import { generateClientFallbackRoadmap } from "@/lib/services/fallback-ai.client";

function getDefaultRoadmap(): LearningRoadmap {
  return generateClientFallbackRoadmap({
    skillLevel: "beginner",
    primaryGoal: "data science and machine learning",
    learningStyle: "hands-on practical learner",
    topCourse: "Data Science Bootcamp",
    quizAccuracy: 67,
    quizWeightedScore: 50,
  });
}

export default function RoadmapPage() {
  const [roadmap, setRoadmap] = useState<LearningRoadmap | null>(null);
  const [studentName, setStudentName] = useState("Your");

  useEffect(() => {
    const stored = sessionStorage.getItem("onboardingResult");
    if (stored) {
      try {
        const data = JSON.parse(stored);
        setRoadmap(data.roadmap);
        setStudentName(data.student?.name || "Your");
      } catch {
        setRoadmap(getDefaultRoadmap());
      }
    } else {
      setRoadmap(getDefaultRoadmap());
    }
  }, []);

  if (!roadmap) return (
    <AppShell>
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin w-8 h-8 border-4 border-[#008F11] border-t-transparent rounded-full" />
      </div>
    </AppShell>
  );

  const isGemini = roadmap.modelUsed === "gemini";

  return (
    <AppShell>
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Header */}
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Map className="w-5 h-5 text-[#008F11]" />
            <h1 className="text-2xl font-bold text-gray-900">{roadmap.roadmapTitle}</h1>
          </div>
          <div className="flex items-center gap-2 mt-2">
            {isGemini ? (
              <StatusBadge label="Generated by Gemini AI" status="ai" />
            ) : (
              <StatusBadge label="AI Fallback Roadmap" status="warning" />
            )}
          </div>
        </div>

        {/* Metrics */}
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          <MetricCard
            title="Career Readiness"
            value={`${roadmap.careerReadinessScore}%`}
            subtitle="Based on your profile"
            icon={Target}
            tone={roadmap.careerReadinessScore >= 65 ? "success" : "warning"}
          />
          <MetricCard
            title="Next Best Lesson"
            value={roadmap.nextBestLesson}
            subtitle="Start here today"
            icon={BookOpen}
            tone="primary"
          />
          <MetricCard
            title="Weak Topic"
            value={roadmap.weakTopic}
            subtitle="Focus area"
            icon={Zap}
            tone="warning"
          />
        </div>

        {/* Summary */}
        <div className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm">
          <h3 className="font-semibold text-gray-800 mb-2 text-sm">Roadmap Summary</h3>
          <p className="text-sm text-gray-600 leading-relaxed">{roadmap.summary}</p>
        </div>

        {/* Timeline */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
          <div className="flex items-center gap-2 mb-5">
            <Map className="w-5 h-5 text-[#008F11]" />
            <h2 className="font-semibold text-gray-800">{studentName}'s Learning Timeline</h2>
          </div>
          <RoadmapTimeline roadmap={roadmap.roadmap} />
        </div>

        {/* Mentor message */}
        <div className="bg-gradient-to-br from-[#008F11]/5 to-[#B7FF4A]/10 rounded-xl border border-[#008F11]/20 p-5">
          <div className="flex items-center gap-2 mb-2">
            <MessageSquare className="w-4 h-4 text-[#008F11]" />
            <h3 className="font-semibold text-gray-800 text-sm">AI Mentor Message</h3>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed">{roadmap.mentorMessage}</p>
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <Link
            href="/student/quiz"
            className="flex-1 bg-[#008F11] hover:bg-[#006B0D] text-white font-medium py-3 rounded-xl text-sm text-center transition-colors"
          >
            Take Adaptive Quiz
          </Link>
          <Link
            href="/student/mentor"
            className="flex-1 bg-[#0B1F33] hover:bg-[#123A5A] text-white font-medium py-3 rounded-xl text-sm text-center transition-colors"
          >
            Ask AI Mentor
          </Link>
        </div>
      </div>
    </AppShell>
  );
}
